var STATES = {

    US_STATE_NAME_TO_CODE                   : {
        'Alabama'                                               : 'AL',
        'Alaska'                                                : 'AK',
        'Arizona'                                               : 'AZ',
        'Arkansas'                                              : 'AR',
        'California'                                            : 'CA',
        'Colorado'                                              : 'CO',
        'Connecticut'                                           : 'CT',
        'Delaware'                                              : 'DE',
        'Florida'                                               : 'FL',
        'Georgia'                                               : 'GA',
        'Hawaii'                                                : 'HI',
        'Idaho'                                                 : 'ID',
        'Illinois'                                              : 'IL',
        'Indiana'                                               : 'IN',
        'Iowa'                                                  : 'IA',
        'Kansas'                                                : 'KS',
        'Kentucky'                                              : 'KY',
        'Louisiana'                                             : 'LA',
        'Maine'                                                 : 'ME',
        'Maryland'                                              : 'MD',
        'Massachusetts'                                         : 'MA',
        'Michigan'                                              : 'MI',
        'Minnesota'                                             : 'MN',
        'Mississippi'                                           : 'MS',
        'Missouri'                                              : 'MO',
        'Montana'                                               : 'MT',
        'Nebraska'                                              : 'NE',
        'Nevada'                                                : 'NV',
        'New Hampshire'                                         : 'NH',
        'New Jersey'                                            : 'NJ',
        'New Mexico'                                            : 'NM',
        'New York'                                              : 'NY',
        'North Carolina'                                        : 'NC',
        'North Dakota'                                          : 'ND',
        'Ohio'                                                  : 'OH',
        'Oklahoma'                                              : 'OK',
        'Oregon'                                                : 'OR',
        'Pennsylvania'                                          : 'PA',
        'Rhode Island'                                          : 'RI',
        'South Carolina'                                        : 'SC',
        'South Dakota'                                          : 'SD',
        'Tennessee'                                             : 'TN',
        'Texas'                                                 : 'TX',
        'Utah'                                                  : 'UT',
        'Vermont'                                               : 'VT',
        'Virginia'                                              : 'VA',
        'Washington'                                            : 'WA',
        'West Virginia'                                         : 'WV',
        'Wisconsin'                                             : 'WI',
        'Wyoming'                                               : 'WY'
    },

    US_INHABITED_TERRITORIES_NAME_TO_CODE   : {
        'American Samoa'                                        : 'AS',
        'Guam'                                                  : 'GU',
        'Northern Mariana Islands'                              : 'MP',
        'Puerto Rico'                                           : 'PR',
        'Virgin Islands'                                        : 'VI',
        'District Of Columbia'                                  : 'DC',   // This is federal district
        'Marshall Islands'                                      : 'MH',   // This is an associated state
        'Palau'                                                 : 'PW',   // This is an associated state
        'Federated States of Micronesia'                        : 'FM'    // This is an associated state
    },

    US_STATE_NAME_TO_CAPITAL                : {
        'Alabama'                                               : 'Montgomery',
        'Alaska'                                                : 'Juneau',
        'Arizona'                                               : 'Phoenix',
        'Arkansas'                                              : 'Little Rock',
        'California'                                            : 'Sacramento',
        'Colorado'                                              : 'Denver',
        'Connecticut'                                           : 'Hartford',
        'Delaware'                                              : 'Dover',
        'Florida'                                               : 'Tallahassee',
        'Georgia'                                               : 'Atlanta',
        'Hawaii'                                                : 'Honolulu',
        'Idaho'                                                 : 'Boise',
        'Illinois'                                              : 'Springfield',
        'Indiana'                                               : 'Indianapolis',
        'Iowa'                                                  : 'Des Moines',
        'Kansas'                                                : 'Topeka',
        'Kentucky'                                              : 'Frankfort',
        'Louisiana'                                             : 'Baton Rouge',
        'Maine'                                                 : 'Augusta',
        'Maryland'                                              : 'Annapolis',
        'Massachusetts'                                         : 'Boston',
        'Michigan'                                              : 'Lansing',
        'Minnesota'                                             : 'Minneapolis',
        'Mississippi'                                           : 'Jackson',
        'Missouri'                                              : 'Jefferson City',
        'Montana'                                               : 'Helena',
        'Nebraska'                                              : 'Lincoln',
        'Nevada'                                                : 'Carson City',
        'New Hampshire'                                         : 'Concord',
        'New Jersey'                                            : 'Trenton',
        'New Mexico'                                            : 'Santa Fe',
        'New York'                                              : 'Albany',
        'North Carolina'                                        : 'Raleigh',
        'North Dakota'                                          : 'Bismarck',
        'Ohio'                                                  : 'Columbus',
        'Oklahoma'                                              : 'Oklahoma City',
        'Oregon'                                                : 'Salem',
        'Pennsylvania'                                          : 'Harrisburg',
        'Rhode Island'                                          : 'Providence',
        'South Carolina'                                        : 'Columbia',
        'South Dakota'                                          : 'Pierre',
        'Tennessee'                                             : 'Nashville',
        'Texas'                                                 : 'Austin',
        'Utah'                                                  : 'Salt Lake City',
        'Vermont'                                               : 'Montpelier',
        'Virginia'                                              : 'Richmond',
        'Washington'                                            : 'Olympia',
        'West Virginia'                                         : 'Charleston',
        'Wisconsin'                                             : 'Madison',
        'Wyoming'                                               : 'Cheyenne',
    },

    US_INHABITED_TERRITORIES_NAME_TO_CAPITAL: {
        'American Samoa'                                        : 'Pago Pago',
        'Guam'                                                  : 'Hagatna',
        'Northern Mariana Islands'                              : 'Saipan',
        'Puerto Rico'                                           : 'San Juan',
        'Virgin Islands'                                        : 'Charlotte Amalie',
        'Marshall Islands'                                      : 'Majuro',         // This is an associated state
        'Palau'                                                 : 'Ngerulmud',      // This is an associated state
        'Federated States of Micronesia'                        : 'Palikir'         // This is an associated state
    }
};

exports = module.exports = STATES;